openage::renderer::resources::MeshData
std::vector<uint8_t> openage::renderer::resources::MeshData::data
The raw vertex data. The size is an integer multiple of the size of a single vertex.
Referenced by openage.convert.dataformat.content_snippet.ContentSnippet.__eq__, openage.convert.dataformat.struct_snippet.StructSnippet.__hash__, openage.convert.dataformat.content_snippet.ContentSnippet.__hash__, openage.convert.dataformat.content_snippet.ContentSnippet.__repr__, openage.convert.dataformat.data_definition.DataDefinition.__str__, openage.convert.dataformat.content_snippet.ContentSnippet.__str__, openage.convert.dataformat.data_formatter.DataFormatter.add_data, openage.convert.dataformat.data_formatter.DataFormatter.export, openage.convert.dataformat.data_definition.DataDefinition.generate_csv, openage.convert.dataformat.content_snippet.ContentSnippet.get_data, openage.convert.texture.TextureImage.get_data, get_data, openage.convert.texture.TextureImage.get_pil_image, openage.convert.peresource.PEResources.read_directory.
std::optional<std::vector<uint8_t> > openage::renderer::resources::MeshData::ids
The indices of vertices to be drawn if the mesh is indexed.
For array drawing, empty optional.
Referenced by get_ids.
std::optional<VertexInputInfo> openage::renderer::resources::MeshData::info
Information about how to interpret the data to make vertices.
This is optional because initialization is deferred until the constructor obtains the mesh data e.g. from disk, but it should always be present after construction.
Referenced by get_info, make_quad.
openage::renderer::resources::MeshData::MeshData(const util::Path &)
Tries to load the mesh data from the specified file.
Referenced by make_quad.
openage::renderer::resources::MeshData::MeshData(std::vector< uint8_t > &&verts, VertexInputInfo)
Initializes the mesh data to a custom unindexed vertex vector described by the given info.
References openage::move.
openage::renderer::resources::MeshData::MeshData(std::vector< uint8_t > &&verts, std::vector< uint8_t > &&ids, VertexInputInfo)
Initializes the mesh data to a custom indexed vertex vector described by the given info.
References openage::move.
std::vector< uint8_t > const & openage::renderer::resources::MeshData::get_data() const
Returns the raw vertex data.
References data.
Referenced by openage::renderer::opengl::GlGeometry::GlGeometry.
std::optional< std::vector< uint8_t > > const & openage::renderer::resources::MeshData::get_ids() const
Returns the indices used for indexed drawing if they exist.
References ids.
VertexInputInfo openage::renderer::resources::MeshData::get_info() const
Returns information describing the vertices in this mesh.
References info.
Referenced by openage::renderer::opengl::GlGeometry::GlGeometry.
MeshData openage::renderer::resources::MeshData::make_quad()
Initializes the mesh data with a simple quadrilateral spanning the whole window space, with (vec2 pos, vec2 uv) vertex format.
References openage::renderer::resources::AOS, info, MeshData, openage::move, openage::renderer::resources::TRIANGLE_STRIP, openage::renderer::resources::V2F32.
Referenced by openage::renderer::tests::renderer_demo_0.