openage::renderer::Window
using openage::renderer::Window::key_cb_t = std::function<void(SDL_KeyboardEvent const&)>
using openage::renderer::Window::mouse_button_cb_t = std::function<void(SDL_MouseButtonEvent const&)>
using openage::renderer::Window::mouse_wheel_cb_t = std::function<void(SDL_MouseWheelEvent const&)>
using openage::renderer::Window::resize_cb_t = std::function<void(size_t, size_t)>
bool openage::renderer::Window::should_be_closed
Referenced by should_close, openage::renderer::opengl::GlWindow::update.
std::pair<size_t, size_t> openage::renderer::Window::size
The current size of the framebuffer.
Referenced by openage.util.bytequeue.ByteQueue.__len__, openage.util.bytequeue.ByteQueue.append, get_size, openage.util.filelike.stream.StreamFragment.get_size, openage::renderer::opengl::GlWindow::GlWindow, openage.util.bytequeue.ByteQueue.popleft, openage.util.filelike.stream.StreamFragment.read, openage::renderer::opengl::GlWindow::set_size, openage::renderer::opengl::GlWindow::update, openage::renderer::vulkan::VlkWindow::VlkWindow.
std::vector<key_cb_t> openage::renderer::Window::on_key
Referenced by add_key_callback, openage::renderer::opengl::GlWindow::update.
std::vector<mouse_button_cb_t> openage::renderer::Window::on_mouse_button
Referenced by add_mouse_button_callback, openage::renderer::opengl::GlWindow::update.
std::vector<mouse_wheel_cb_t> openage::renderer::Window::on_mouse_wheel
Referenced by add_mouse_wheel_callback.
std::vector<resize_cb_t> openage::renderer::Window::on_resize
Referenced by add_resize_callback, openage::renderer::opengl::GlWindow::set_size, openage::renderer::opengl::GlWindow::update.
virtual openage::renderer::Window::~Window()=default
std::pair< size_t, size_t > openage::renderer::Window::get_size() const
Returns the dimensions of this window.
References size.
Referenced by openage::renderer::tests::renderer_demo_0, openage.util.filelike.abstract.FileLikeObject.seek_helper.
bool openage::renderer::Window::should_close() const
Returns true if this window should be closed.
References should_be_closed.
Referenced by openage::renderer::tests::renderer_demo_0.
void openage::renderer::Window::add_key_callback(const key_cb_t &)
References on_key.
void openage::renderer::Window::add_mouse_button_callback(const mouse_button_cb_t &)
References on_mouse_button.
Referenced by openage::renderer::tests::renderer_demo_0.
void openage::renderer::Window::add_mouse_wheel_callback(const mouse_wheel_cb_t &)
References on_mouse_wheel.
void openage::renderer::Window::add_resize_callback(const resize_cb_t &)
References on_resize.
Referenced by openage::renderer::opengl::GlWindow::GlWindow, openage::renderer::tests::renderer_demo_0.
virtual void openage::renderer::Window::set_size(size_t width, size_t height)=0
Force the window to the given size.
It's generally not a good idea to use this, as it makes the window jump around wierdly.
virtual void openage::renderer::Window::update()=0
Polls for window events, calls callbacks for these events, swaps front and back framebuffers to present graphics onto screen.
This has to be called at the end of every graphics frame.
virtual std::unique_ptr<Renderer> openage::renderer::Window::make_renderer()=0
Creates a renderer which uses the window's graphics API and targets the window.
openage::renderer::Window::Window(size_t width, size_t height)