openage::GameMainSignals
void openage::GameMainSignals::game_running(bool running)
Referenced by openage::GameMainHandle::announce_running, openage::gui::GameMainLink::on_core_adopted, openage::GameControl::set_game.