openage::console::draw
void openage::console::draw::to_opengl(Engine *engine, Console *console)
experimental and totally inefficient opengl draw of a terminal buffer.
References openage::console::buf_char::bgcol, openage::console::Console::bottomleft, openage::console::Console::buf, openage::console::Console::charsize, openage::console::CHR_BLINKING, openage::console::CHR_BLINKINGFAST, openage::console::CHR_INVISIBLE, openage::console::CHR_NEGATIVE, openage::console::Buf::chrdataptr, openage::console::buf_char::cp, openage::console::Buf::cursor_visible, openage::console::Buf::cursorpos, openage::console::Buf::dims, openage::renderer::TextRenderer::draw, openage::console::buf_char::fgcol, openage::console::buf_char::flags, openage::console::Console::font, openage::renderer::Font::get_ascender, openage::timing::get_monotonic_time, openage::Engine::get_text_renderer, openage::console::Buf::scrollback_pos, openage::renderer::TextRenderer::set_font, openage::console::Console::termcolors, openage::util::utf8_encode.
Referenced by openage::console::Console::on_drawhud.
void openage::console::draw::to_terminal(Buf *buf, util::FD *fd, bool clear=false)
very early and inefficient printing of the console to a pty.
References openage::console::buf_char::bgcol, openage::console::CHR_BLINKING, openage::console::CHR_BOLD, openage::console::CHR_NEGATIVE, openage::console::Buf::chrdataptr, openage::console::buf_char::cp, openage::console::Buf::cursor_visible, openage::console::Buf::cursorpos, openage::console::Buf::dims, openage::console::buf_char::fgcol, openage::console::buf_char::flags, openage::util::FD::printf, openage::util::FD::putbyte, openage::util::FD::putcp, openage::util::FD::puts, openage::console::Buf::scrollback_pos, openage::console::Buf::scrollback_possible, openage::console::Buf::title.
Referenced by openage::console::tests::interactive, openage::console::tests::render.