var namespaceqtsdl =
[
    [ "can_call", "da/d24/structqtsdl_1_1can__call.xhtml", null ],
    [ "can_call_test", "de/d6a/structqtsdl_1_1can__call__test.xhtml", "de/d6a/structqtsdl_1_1can__call__test" ],
    [ "CtxExtractionException", "d5/d5f/classqtsdl_1_1_ctx_extraction_exception.xhtml", "d5/d5f/classqtsdl_1_1_ctx_extraction_exception" ],
    [ "CtxExtractionMode", "df/dcb/classqtsdl_1_1_ctx_extraction_mode.xhtml", "df/dcb/classqtsdl_1_1_ctx_extraction_mode" ],
    [ "DeferredInitialConstantPropertyValues", "df/dc7/classqtsdl_1_1_deferred_initial_constant_property_values.xhtml", "df/dc7/classqtsdl_1_1_deferred_initial_constant_property_values" ],
    [ "EventHandlingQuickWindow", "dd/dee/classqtsdl_1_1_event_handling_quick_window.xhtml", "dd/dee/classqtsdl_1_1_event_handling_quick_window" ],
    [ "GameLogicCaller", "d0/d88/classqtsdl_1_1_game_logic_caller.xhtml", "d0/d88/classqtsdl_1_1_game_logic_caller" ],
    [ "gl_debug_parameters", "de/deb/structqtsdl_1_1gl__debug__parameters.xhtml", "de/deb/structqtsdl_1_1gl__debug__parameters" ],
    [ "GuiApplication", "dc/d0a/classqtsdl_1_1_gui_application.xhtml", "dc/d0a/classqtsdl_1_1_gui_application" ],
    [ "GuiApplicationImpl", "dc/d99/classqtsdl_1_1_gui_application_impl.xhtml", "dc/d99/classqtsdl_1_1_gui_application_impl" ],
    [ "GuiCallback", "d9/df2/classqtsdl_1_1_gui_callback.xhtml", "d9/df2/classqtsdl_1_1_gui_callback" ],
    [ "GuiDedicatedThread", "df/d66/classqtsdl_1_1_gui_dedicated_thread.xhtml", "df/d66/classqtsdl_1_1_gui_dedicated_thread" ],
    [ "GuiEngine", "d8/d14/classqtsdl_1_1_gui_engine.xhtml", "d8/d14/classqtsdl_1_1_gui_engine" ],
    [ "GuiEngineImpl", "de/d58/classqtsdl_1_1_gui_engine_impl.xhtml", "de/d58/classqtsdl_1_1_gui_engine_impl" ],
    [ "GuiEngineImplConnection", "dd/d89/classqtsdl_1_1_gui_engine_impl_connection.xhtml", "dd/d89/classqtsdl_1_1_gui_engine_impl_connection" ],
    [ "GuiEventQueue", "d7/dc9/classqtsdl_1_1_gui_event_queue.xhtml", "d7/dc9/classqtsdl_1_1_gui_event_queue" ],
    [ "GuiEventQueueImpl", "dc/dc7/classqtsdl_1_1_gui_event_queue_impl.xhtml", "dc/dc7/classqtsdl_1_1_gui_event_queue_impl" ],
    [ "GuiImageProvider", "d5/df5/classqtsdl_1_1_gui_image_provider.xhtml", "d5/df5/classqtsdl_1_1_gui_image_provider" ],
    [ "GuiImageProviderImpl", "db/d28/classqtsdl_1_1_gui_image_provider_impl.xhtml", "db/d28/classqtsdl_1_1_gui_image_provider_impl" ],
    [ "GuiInput", "de/dfb/classqtsdl_1_1_gui_input.xhtml", "de/dfb/classqtsdl_1_1_gui_input" ],
    [ "GuiInputImpl", "d3/dac/classqtsdl_1_1_gui_input_impl.xhtml", "d3/dac/classqtsdl_1_1_gui_input_impl" ],
    [ "GuiItem", "dd/d7b/classqtsdl_1_1_gui_item.xhtml", "dd/d7b/classqtsdl_1_1_gui_item" ],
    [ "GuiItemBase", "d3/d71/classqtsdl_1_1_gui_item_base.xhtml", "d3/d71/classqtsdl_1_1_gui_item_base" ],
    [ "GuiItemCoreInstantiator", "df/df5/classqtsdl_1_1_gui_item_core_instantiator.xhtml", "df/df5/classqtsdl_1_1_gui_item_core_instantiator" ],
    [ "GuiItemInterface", "d2/dac/classqtsdl_1_1_gui_item_interface.xhtml", "d2/dac/classqtsdl_1_1_gui_item_interface" ],
    [ "GuiItemLink", "da/dff/classqtsdl_1_1_gui_item_link.xhtml", "da/dff/classqtsdl_1_1_gui_item_link" ],
    [ "GuiItemListModel", "d6/d56/classqtsdl_1_1_gui_item_list_model.xhtml", "d6/d56/classqtsdl_1_1_gui_item_list_model" ],
    [ "GuiItemMethods", "d5/db2/classqtsdl_1_1_gui_item_methods.xhtml", "d5/db2/classqtsdl_1_1_gui_item_methods" ],
    [ "GuiItemOrigin", "d9/db0/classqtsdl_1_1_gui_item_origin.xhtml", "d9/db0/classqtsdl_1_1_gui_item_origin" ],
    [ "GuiItemQObject", "de/dbd/classqtsdl_1_1_gui_item_q_object.xhtml", "de/dbd/classqtsdl_1_1_gui_item_q_object" ],
    [ "GuiListModel", "d0/d73/classqtsdl_1_1_gui_list_model.xhtml", "d0/d73/classqtsdl_1_1_gui_list_model" ],
    [ "GuiLiveReloader", "da/d61/classqtsdl_1_1_gui_live_reloader.xhtml", "da/d61/classqtsdl_1_1_gui_live_reloader" ],
    [ "GuiLiveReloaderAttachedProperty", "d0/dc9/classqtsdl_1_1_gui_live_reloader_attached_property.xhtml", "d0/dc9/classqtsdl_1_1_gui_live_reloader_attached_property" ],
    [ "GuiLiveReloaderAttachedPropertyProvider", "d8/d4a/classqtsdl_1_1_gui_live_reloader_attached_property_provider.xhtml", "d8/d4a/classqtsdl_1_1_gui_live_reloader_attached_property_provider" ],
    [ "GuiPropertyMap", "db/d4f/structqtsdl_1_1_gui_property_map.xhtml", "db/d4f/structqtsdl_1_1_gui_property_map" ],
    [ "GuiPropertyMapImpl", "da/d54/classqtsdl_1_1_gui_property_map_impl.xhtml", "da/d54/classqtsdl_1_1_gui_property_map_impl" ],
    [ "GuiRenderer", "d0/d58/classqtsdl_1_1_gui_renderer.xhtml", "d0/d58/classqtsdl_1_1_gui_renderer" ],
    [ "GuiRendererImpl", "dd/db2/classqtsdl_1_1_gui_renderer_impl.xhtml", "dd/db2/classqtsdl_1_1_gui_renderer_impl" ],
    [ "GuiRenderingCtxActivator", "d4/d21/classqtsdl_1_1_gui_rendering_ctx_activator.xhtml", "d4/d21/classqtsdl_1_1_gui_rendering_ctx_activator" ],
    [ "GuiRenderingSetupRoutines", "d1/df3/classqtsdl_1_1_gui_rendering_setup_routines.xhtml", "d1/df3/classqtsdl_1_1_gui_rendering_setup_routines" ],
    [ "GuiSeparateRenderingContext", "d2/d67/classqtsdl_1_1_gui_separate_rendering_context.xhtml", "d2/d67/classqtsdl_1_1_gui_separate_rendering_context" ],
    [ "GuiSingletonItem", "da/de2/classqtsdl_1_1_gui_singleton_item.xhtml", "da/de2/classqtsdl_1_1_gui_singleton_item" ],
    [ "GuiSingletonItemsInfo", "d2/dbf/classqtsdl_1_1_gui_singleton_items_info.xhtml", null ],
    [ "GuiSubtree", "d8/de9/classqtsdl_1_1_gui_subtree.xhtml", "d8/de9/classqtsdl_1_1_gui_subtree" ],
    [ "GuiSubtreeImpl", "d4/d96/classqtsdl_1_1_gui_subtree_impl.xhtml", "d4/d96/classqtsdl_1_1_gui_subtree_impl" ],
    [ "GuiUniqueRenderingContext", "d6/dec/classqtsdl_1_1_gui_unique_rendering_context.xhtml", "d6/dec/classqtsdl_1_1_gui_unique_rendering_context" ],
    [ "Inherits", "d2/d2f/classqtsdl_1_1_inherits.xhtml", "d2/d2f/classqtsdl_1_1_inherits" ],
    [ "PersistentCoreHolder", "d5/ddf/classqtsdl_1_1_persistent_core_holder.xhtml", "d5/ddf/classqtsdl_1_1_persistent_core_holder" ],
    [ "PersistentCoreHolderBase", "df/db1/classqtsdl_1_1_persistent_core_holder_base.xhtml", "df/db1/classqtsdl_1_1_persistent_core_holder_base" ],
    [ "QmlEngineWithSingletonItemsInfo", "d1/dd2/classqtsdl_1_1_qml_engine_with_singleton_items_info.xhtml", "d1/dd2/classqtsdl_1_1_qml_engine_with_singleton_items_info" ],
    [ "RecursiveDirectoryWatcher", "d3/dea/classqtsdl_1_1_recursive_directory_watcher.xhtml", "d3/dea/classqtsdl_1_1_recursive_directory_watcher" ],
    [ "RecursiveDirectoryWatcherWorker", "dc/d7b/classqtsdl_1_1_recursive_directory_watcher_worker.xhtml", "dc/d7b/classqtsdl_1_1_recursive_directory_watcher_worker" ],
    [ "Shadow", "d1/d28/classqtsdl_1_1_shadow.xhtml", "d1/d28/classqtsdl_1_1_shadow" ],
    [ "TemporaryDisableGuiRendererSync", "d6/da8/classqtsdl_1_1_temporary_disable_gui_renderer_sync.xhtml", "d6/da8/classqtsdl_1_1_temporary_disable_gui_renderer_sync" ],
    [ "Unwrap", "d1/d78/structqtsdl_1_1_unwrap.xhtml", null ],
    [ "Unwrap< openage::gui::ActionModeLink >", "d9/db5/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_action_mode_link_01_4.xhtml", "d9/db5/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_action_mode_link_01_4" ],
    [ "Unwrap< openage::gui::AssetManagerLink >", "d9/d82/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_asset_manager_link_01_4.xhtml", "d9/d82/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_asset_manager_link_01_4" ],
    [ "Unwrap< openage::gui::CreateModeLink >", "d1/d78/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_create_mode_link_01_4.xhtml", "d1/d78/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_create_mode_link_01_4" ],
    [ "Unwrap< openage::gui::EditorModeLink >", "d5/dc3/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_editor_mode_link_01_4.xhtml", "d5/dc3/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_editor_mode_link_01_4" ],
    [ "Unwrap< openage::gui::EngineLink >", "dd/dab/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_engine_link_01_4.xhtml", "dd/dab/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_engine_link_01_4" ],
    [ "Unwrap< openage::gui::GameControlLink >", "d5/d86/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_game_control_link_01_4.xhtml", "d5/d86/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_game_control_link_01_4" ],
    [ "Unwrap< openage::gui::GameMainLink >", "d7/d97/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_game_main_link_01_4.xhtml", "d7/d97/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_game_main_link_01_4" ],
    [ "Unwrap< openage::gui::GameSpecLink >", "df/d05/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_game_spec_link_01_4.xhtml", "df/d05/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_game_spec_link_01_4" ],
    [ "Unwrap< openage::gui::GeneratorLink >", "d2/d3b/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_generator_link_01_4.xhtml", "d2/d3b/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_generator_link_01_4" ],
    [ "Unwrap< openage::gui::OutputModeLink >", "db/d90/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_output_mode_link_01_4.xhtml", "db/d90/structqtsdl_1_1_unwrap_3_01openage_1_1gui_1_1_output_mode_link_01_4" ],
    [ "Wrap", "df/d03/structqtsdl_1_1_wrap.xhtml", null ],
    [ "Wrap< openage::ActionMode >", "d1/d02/structqtsdl_1_1_wrap_3_01openage_1_1_action_mode_01_4.xhtml", "d1/d02/structqtsdl_1_1_wrap_3_01openage_1_1_action_mode_01_4" ],
    [ "Wrap< openage::AssetManager >", "d7/da2/structqtsdl_1_1_wrap_3_01openage_1_1_asset_manager_01_4.xhtml", "d7/da2/structqtsdl_1_1_wrap_3_01openage_1_1_asset_manager_01_4" ],
    [ "Wrap< openage::CreateMode >", "d0/d27/structqtsdl_1_1_wrap_3_01openage_1_1_create_mode_01_4.xhtml", "d0/d27/structqtsdl_1_1_wrap_3_01openage_1_1_create_mode_01_4" ],
    [ "Wrap< openage::EditorMode >", "db/dd6/structqtsdl_1_1_wrap_3_01openage_1_1_editor_mode_01_4.xhtml", "db/dd6/structqtsdl_1_1_wrap_3_01openage_1_1_editor_mode_01_4" ],
    [ "Wrap< openage::Engine >", "dd/de2/structqtsdl_1_1_wrap_3_01openage_1_1_engine_01_4.xhtml", "dd/de2/structqtsdl_1_1_wrap_3_01openage_1_1_engine_01_4" ],
    [ "Wrap< openage::GameControl >", "d3/d75/structqtsdl_1_1_wrap_3_01openage_1_1_game_control_01_4.xhtml", "d3/d75/structqtsdl_1_1_wrap_3_01openage_1_1_game_control_01_4" ],
    [ "Wrap< openage::GameMainHandle >", "d7/d98/structqtsdl_1_1_wrap_3_01openage_1_1_game_main_handle_01_4.xhtml", "d7/d98/structqtsdl_1_1_wrap_3_01openage_1_1_game_main_handle_01_4" ],
    [ "Wrap< openage::GameSpecHandle >", "db/df0/structqtsdl_1_1_wrap_3_01openage_1_1_game_spec_handle_01_4.xhtml", "db/df0/structqtsdl_1_1_wrap_3_01openage_1_1_game_spec_handle_01_4" ],
    [ "Wrap< openage::Generator >", "d6/df8/structqtsdl_1_1_wrap_3_01openage_1_1_generator_01_4.xhtml", "d6/df8/structqtsdl_1_1_wrap_3_01openage_1_1_generator_01_4" ],
    [ "Wrap< openage::OutputMode >", "d4/dc8/structqtsdl_1_1_wrap_3_01openage_1_1_output_mode_01_4.xhtml", "d4/dc8/structqtsdl_1_1_wrap_3_01openage_1_1_output_mode_01_4" ]
];