qtsdl::GuiPropertyMap
std::unique_ptr<GuiPropertyMapImpl> qtsdl::GuiPropertyMap::impl
Referenced by get_csv, getv, qtsdl::GuiPropertyMap::getv< std::string >, qtsdl::GuiPropertyMap::getv< std::vector< std::string > >, qtsdl::GuiPropertyMap::setv< const std::string & >, qtsdl::GuiPropertyMap::setv< const std::vector< std::string > & >, set_csv, setv.
qtsdl::GuiPropertyMap::GuiPropertyMap()
qtsdl::GuiPropertyMap::~GuiPropertyMap()
References map, openage.testing.testing.result.
T qtsdl::GuiPropertyMap::getv(const char *name) const
T qtsdl::GuiPropertyMap::getv(const std::string &name) const
References get_csv.
std::vector< std::string > qtsdl::GuiPropertyMap::get_csv(const char *name) const
References impl, openage::util::split.
Referenced by get_csv, getv, openage::Generator::player_names.
std::vector<std::string> qtsdl::GuiPropertyMap::get_csv(const std::string &name) const
References get_csv, setv.
void qtsdl::GuiPropertyMap::setv(const char *name, T v)
Referenced by openage::Generator::Generator, get_csv, set_csv.
void qtsdl::GuiPropertyMap::setv(const std::string &name, T v)
References set_csv.
void qtsdl::GuiPropertyMap::set_csv(const char *name, const std::vector< std::string > &v)
References impl.
Referenced by openage::Generator::Generator, set_csv, setv.
void qtsdl::GuiPropertyMap::set_csv(const std::string &name, const std::vector< std::string > &v)
References set_csv, setv.
void qtsdl::GuiPropertyMap::setv(const char *name, const std::string &v)
void qtsdl::GuiPropertyMap::setv(const std::string &name, const std::string &v)
void qtsdl::GuiPropertyMap::setv(const char *name, const std::vector< std::string > &v)
void qtsdl::GuiPropertyMap::setv(const std::string &name, const std::vector< std::string > &v)
bool qtsdl::GuiPropertyMap::getv(const char *name) const
References impl.
void qtsdl::GuiPropertyMap::setv(const char *name, bool v)
References impl.
int qtsdl::GuiPropertyMap::getv(const char *name) const
References impl.
void qtsdl::GuiPropertyMap::setv(const char *name, int v)
References impl.
double qtsdl::GuiPropertyMap::getv(const char *name) const
References impl.
void qtsdl::GuiPropertyMap::setv(const char *name, double v)
References impl.
void qtsdl::GuiPropertyMap::setv(const char *name, const char *v)
References impl.
QString qtsdl::GuiPropertyMap::getv(const char *name) const
References impl.
void qtsdl::GuiPropertyMap::setv(const char *name, const QString &v)
References impl.
QStringList qtsdl::GuiPropertyMap::getv(const char *name) const
References impl.
void qtsdl::GuiPropertyMap::setv(const char *name, const QStringList &v)
References impl.
bool qtsdl::GuiPropertyMap::getv(const char *name) const
void qtsdl::GuiPropertyMap::setv(const char *name, bool v)
int qtsdl::GuiPropertyMap::getv(const char *name) const
void qtsdl::GuiPropertyMap::setv(const char *name, int v)
double qtsdl::GuiPropertyMap::getv(const char *name) const
void qtsdl::GuiPropertyMap::setv(const char *name, double v)
std::string qtsdl::GuiPropertyMap::getv(const char *name) const
void qtsdl::GuiPropertyMap::setv(const char *name, const std::string &v)
void qtsdl::GuiPropertyMap::setv(const char *name, const char *v)
std::vector<std::string> qtsdl::GuiPropertyMap::getv(const char *name) const