openage::datastructure::ConstMap
std::array<std::pair<K, V>, count> openage::datastructure::ConstMap< K, V, count >::values
The entries associated with this map.
Referenced by openage::datastructure::ConstMap< K, V, count >::contains, openage::datastructure::ConstMap< K, V, count >::find, openage.convert.dataformat.members.EnumMember.format_hash, openage::datastructure::ConstMap< K, V, count >::get, openage.convert.dataformat.members.EnumMember.get_parsers, openage.convert.dataformat.members.EnumMember.get_snippets, openage.convert.dataformat.members.EnumMember.validate_value, openage::datastructure::ConstMap< K, V, count >::verify_no_duplicates.
constexpr openage::datastructure::ConstMap< K, V, count >::ConstMap(Entries &&... entries)
References openage::datastructure::ConstMap< K, V, count >::verify_no_duplicates.
Referenced by openage::datastructure::create_const_map.
constexpr int openage::datastructure::ConstMap< K, V, count >::size() const
Return the number of entries in this map.
constexpr bool openage::datastructure::ConstMap< K, V, count >::contains(const K &key) const
Tests if the given key is in this map.
References openage::datastructure::ConstMap< K, V, count >::find, openage::datastructure::ConstMap< K, V, count >::values.
Referenced by openage::datastructure::tests::constexpr_map.
constexpr const V& openage::datastructure::ConstMap< K, V, count >::get(const K &key) const
Return the stored value for the given key.
References openage::log.err, openage::datastructure::ConstMap< K, V, count >::find, MSG, openage::datastructure::ConstMap< K, V, count >::values.
constexpr const V& openage::datastructure::ConstMap< K, V, count >::operator[](const K &key) const
Access entries by map[key].
constexpr void openage::datastructure::ConstMap< K, V, count >::verify_no_duplicates() const
Abort when the map uses the same key more than once.
References openage::log.err, MSG, openage::datastructure::ConstMap< K, V, count >::values.
Referenced by openage::datastructure::ConstMap< K, V, count >::ConstMap.
constexpr auto openage::datastructure::ConstMap< K, V, count >::find(const K &key) const
Returns the iterator matching key from the array.
values.end() if the key is not found.
References openage::datastructure::ConstMap< K, V, count >::values.
Referenced by openage::datastructure::ConstMap< K, V, count >::contains, openage::datastructure::ConstMap< K, V, count >::get.