openage::gui
openage::gui::current_type_id
openage::gui::current_terrain_id
Referenced by openage::EditorMode::set_current_terrain_id.
openage::gui::paint_terrain
openage::gui::QQmlParserStatus
Referenced by openage::gui::GameMainLink::GameMainLink, openage::gui::GameSpecLink::GameSpecLink, openage::gui::OutputModeLink::OutputModeLink.
openage::gui::GuiItem
openage::gui::mode
Referenced by openage::renderer::vulkan::VlkDrawableDisplay::choose_best_present_mode, openage::Texture::draw, openage::util::File::File, openage::GameControl::set_modes, openage::input::InputManager::set_relative, openage::renderer::vulkan::VlkDrawableDisplay::VlkDrawableDisplay.
openage::gui::effective_mode_index
openage::gui::mode_index
Referenced by openage::GameControl::set_mode.
openage::gui::engine
Referenced by openage::ActionMode::announce_buttons_type, openage::ActionMode::available, openage::Unit::draw, openage::gui::EngineLink::EngineLink, openage::ActionMode::get_action, qtsdl::GuiSubtree::GuiSubtree, openage::MoveAction::initialise, openage::Unit::make_location, openage::ActionModeSignals::on_action, openage::ActionMode::on_exit, openage::ActionMode::on_game_control_set, openage::EditorMode::on_game_control_set, openage::EditorMode::paint_entity_at, openage::EditorMode::paint_terrain_at, openage::ActionMode::place_selection, openage::gui::MainArgsLink::provider, openage::gui::GuiImageProviderLink::provider, openage::gui::EngineLink::provider, openage::ActionMode::render, openage::run_game, openage::UnitAction::~UnitAction.
openage::gui::game
Referenced by openage::Generator::create, openage::ActionMode::get_action, openage::EditorMode::paint_entity_at, openage::ActionMode::render.
const int openage::gui::reg_path
void openage::gui::gui_log(QtMsgType type, const QMessageLogContext &context, const QString &msg)
References openage::log.crit, openage::log.dbg, openage::log.err, openage::log.info, openage::log::log, openage::log.warn.
std::unique_ptr< QSGTexture > openage::gui::make_standalone_subtexture(GLuint id, const QSize &size)
Referenced by openage::gui::GuiTexture::removedFromAtlas.
bool openage::gui::isAtlasTexture(const TextureHandle &texture_handle)
References openage::Texture::get_subtexture_count, openage::gui::TextureHandle::subid, openage::gui::TextureHandle::texture.
Referenced by openage::gui::GuiTexture::isAtlasTexture, native_size.
QSize openage::gui::textureSize(const SizedTextureHandle &texture_handle)
References openage::gui::SizedTextureHandle::size.
Referenced by openage::gui::GuiFilledTextureHandles::fill_all_handles_with_texture, openage::gui::GuiTextureFactory::textureSize, openage::gui::GuiTexture::textureSize.
QSize openage::gui::native_size(const TextureHandle &texture_handle)
References openage::Texture::get_subtexture, isAtlasTexture, openage::gui::TextureHandle::subid, openage::gui::TextureHandle::texture.
Referenced by aspect_fit_size.
QSize openage::gui::aspect_fit_size(const TextureHandle &texture_handle, const QSize &requested_size)
The sourceSize property of the Image QML element ends up here for checking.
requested_size sourceSize if used in Image QML element. if !requested_size.isValid() or requested_size.isNull() then native size, otherwise fit in the requested_size (zero component in requested_size means unbounded).
References native_size, openage::gui::SizedTextureHandle::size.
Referenced by openage::gui::GuiGameSpecImageProviderImpl::overwrite_texture_handle.