openage::renderer
font_direction
geometry_t
This passes 4 vertices with undefined positions to the shader.
The shader has to set the positions itself (e.g. using gl_VertexID in OpenGL).
using openage::renderer::codepoint_t = typedef unsigned int
constexpr int openage::renderer::FREETYPE_UNIT
Referenced by openage::renderer::Font::get_advance_width, openage::renderer::Font::get_ascender, openage::renderer::Font::get_descender, openage::renderer::Font::get_horizontal_kerning, openage::renderer::Font::get_line_height, openage::renderer::Font::initialize, openage::renderer::Font::load_glyph.
* * A shader input mapping is only allowed when there is a single element in buffers In such a openage::renderer::case
static hb_direction_t openage::renderer::get_hb_font_direction(const font_description &description)
References bottom_to_top, openage::renderer::font_description::direction, left_to_right, right_to_left, top_to_bottom.
Referenced by openage::renderer::Font::get_advance_width, openage::renderer::Font::get_glyphs.
static hb_language_t openage::renderer::get_hb_font_language(const font_description &description)
References openage::renderer::font_description::language.
Referenced by openage::renderer::Font::get_advance_width, openage::renderer::Font::get_glyphs.
static hb_script_t openage::renderer::get_hb_font_script(const font_description &description)
References openage::renderer::font_description::script.
Referenced by openage::renderer::Font::get_advance_width, openage::renderer::Font::get_glyphs.
* * A shader input mapping is only allowed when there is a single element in buffers In such a * the vertex inputs are paired with VAO attributes according to the mapping instead of in ascending order* openage::renderer::GlVertexArray(std::vector< std::pair< GlBuffer const &, resources::VertexInputInfo const &>> buffers)
openage::renderer::GlVertexArray(GlBuffer const &, resources::VertexInputInfo const &)
Executes the buffer list constructor with one element.
openage::renderer::GlVertexArray()
The default constructor initializes an empty VAO with no attributes.
This is useful for bufferless drawing.
void openage::renderer::bind() const
Make this vertex array object the current one.
Referenced by qtsdl::GuiItemListModel< GeneratorLink >::GuiItemListModel, openage::gui::GuiGameSpecImageProviderImpl::migrate_to_new_game_spec, openage::event::demo::PongBall::PongBall, openage::event::demo::PongPlayer::PongPlayer.
void openage::renderer::make_sdl_available()
Lazily initializes the global SDL singleton if it isn't yet available, otherwise does nothing.
References openage::renderer::SDL::make_available.
Referenced by openage::renderer::opengl::GlWindow::GlWindow, openage::renderer::vulkan::VlkWindow::VlkWindow.