qtsdl::RecursiveDirectoryWatcherWorker
std::unique_ptr<QFileSystemWatcher> qtsdl::RecursiveDirectoryWatcherWorker::watcher
Actual watcher.
Its event processing and destruction has to be in the same separate thread.
Referenced by restart_watching.
QTimer qtsdl::RecursiveDirectoryWatcherWorker::batching_timer
Waits to glue multiple changes into one event.
Referenced by onEntryChanged, RecursiveDirectoryWatcherWorker.
QStringList qtsdl::RecursiveDirectoryWatcherWorker::root_dirs_paths
Referenced by onRootDirsPathsChanged, restartWatching.
qtsdl::RecursiveDirectoryWatcherWorker::RecursiveDirectoryWatcherWorker()
References batching_timer, changeDetected, restartWatching.
void qtsdl::RecursiveDirectoryWatcherWorker::changeDetected()
Referenced by qtsdl::RecursiveDirectoryWatcher::RecursiveDirectoryWatcher, RecursiveDirectoryWatcherWorker.
void qtsdl::RecursiveDirectoryWatcherWorker::onRootDirsPathsChanged(const QStringList &root_dirs_paths)
References openage::util::for_each, restartWatching, root_dirs_paths.
Referenced by qtsdl::RecursiveDirectoryWatcher::RecursiveDirectoryWatcher.
void qtsdl::RecursiveDirectoryWatcherWorker::restartWatching()
References restart_watching, root_dirs_paths.
Referenced by onRootDirsPathsChanged, RecursiveDirectoryWatcherWorker.
void qtsdl::RecursiveDirectoryWatcherWorker::onEntryChanged()
References batching_timer.
Referenced by restart_watching.
void qtsdl::RecursiveDirectoryWatcherWorker::restart_watching(const QStringList &entries_to_watch)
References onEntryChanged, watcher.
Referenced by restartWatching.