openage::Team
const unsigned int openage::Team::id
unique id of the team
Referenced by operator==, Team.
const std::string openage::Team::name
visible name of this team
Referenced by openage.convert.dataformat.header_snippet.HeaderSnippet.__eq__, openage.convert.dataformat.header_snippet.HeaderSnippet.__hash__, openage.convert.dataformat.header_snippet.HeaderSnippet.__repr__, openage.convert.dataformat.header_snippet.HeaderSnippet.get_file_name, openage.util.fslike.path.Path.stem, openage.util.fslike.path.Path.suffix, openage.util.fslike.path.Path.suffixes, Team.
TeamScore openage::Team::score
The score of the team, based on the team's players score.
Referenced by Team, openage::PlayerScore::update_score.
std::unordered_map<const Player*, member_type> openage::Team::members
Referenced by add_member, change_member_type, openage.convert.dataformat.struct_definition.StructDefinition.dynamic_ref_update, openage.convert.dataformat.struct_snippet.StructSnippet.generate_content, openage.convert.dataformat.data_definition.DataDefinition.generate_csv, openage.convert.dataformat.struct_definition.StructDefinition.generate_struct, openage.convert.dataformat.struct_definition.StructDefinition.generate_struct_implementation, get_member_type, get_players, is_member, remove_member.
openage::Team::Team(unsigned int id)
References id.
openage::Team::Team(unsigned int id, std::string name)
References id, name.
openage::Team::Team(unsigned int id, std::string name, Player *leader)
References add_member, openage::leader, name, score.
bool openage::Team::operator==(const Team &other) const
References id.
void openage::Team::add_member(Player &player, const member_type type)
References members, openage::Player::team.
Referenced by Team.
void openage::Team::change_member_type(Player &player, const member_type type)
References members.
bool openage::Team::is_member(const Player &player) const
References members.
Referenced by openage::Player::is_ally.
void openage::Team::remove_member(Player &player)
References members, openage::Player::team.
member_type openage::Team::get_member_type(Player &player)
References members, openage::none.
std::vector< const Player * > openage::Team::get_players() const
TODO find a better way to get all the players.
References members.
Referenced by openage::TeamScore::update_score.