openage::renderer::tests
void openage::renderer::tests::font_manager_test_get_font()
References font_manager, openage::renderer::FontManager::get_font, TESTFAIL.
Referenced by font_manager.
void openage::renderer::tests::font_manager()
References font_manager_test_get_font.
Referenced by openage::renderer::Font::Font, font_manager_test_get_font.
void openage::renderer::tests::font_test_font_description()
References openage::renderer::font_description::font_file, openage::renderer::font_description::language, openage::renderer::left_to_right, openage::renderer::right_to_left, TESTFAIL.
Referenced by font.
void openage::renderer::tests::font()
References font_test_font_description.
Referenced by openage::renderer::FontManager::get_font, openage::renderer::TextRenderer::render, openage::Engine::render_text, openage::renderer::TextRenderer::set_font.
void openage::renderer::tests::renderer_demo_0(const util::Path &path)
References openage::renderer::Window::add_mouse_button_callback, openage::renderer::Window::add_resize_callback, openage::renderer::opengl::GlContext::check_error, openage::renderer::resources::depth24, openage::renderer::resources::fragment, openage::renderer::Window::get_size, openage::renderer::resources::glsl, INFO, openage::log::log, openage::renderer::resources::MeshData::make_quad, openage::renderer::opengl::GlWindow::make_renderer, openage::renderer::resources::r32ui, openage::renderer::resources::Texture2dData::read_pixel, openage::renderer::resources::rgba8, openage::renderer::Window::should_close, openage::renderer::opengl::GlWindow::update, openage::renderer::resources::vertex.
Referenced by renderer_demo.
OAAPI void openage::renderer::tests::renderer_demo(int demo_id, util::Path path)
References openage::log.err, openage::log::log, MSG, renderer_demo_0.