var namespaceopenage_1_1renderer =
[
    [ "opengl", "d0/dc7/namespaceopenage_1_1renderer_1_1opengl.xhtml", "d0/dc7/namespaceopenage_1_1renderer_1_1opengl" ],
    [ "resources", "d1/d65/namespaceopenage_1_1renderer_1_1resources.xhtml", "d1/d65/namespaceopenage_1_1renderer_1_1resources" ],
    [ "vulkan", "d5/ddf/namespaceopenage_1_1renderer_1_1vulkan.xhtml", "d5/ddf/namespaceopenage_1_1renderer_1_1vulkan" ],
    [ "Color", "da/ded/classopenage_1_1renderer_1_1_color.xhtml", "da/ded/classopenage_1_1renderer_1_1_color" ],
    [ "Colors", "d7/d4d/classopenage_1_1renderer_1_1_colors.xhtml", "d7/d4d/classopenage_1_1renderer_1_1_colors" ],
    [ "Font", "df/db8/classopenage_1_1renderer_1_1_font.xhtml", "df/db8/classopenage_1_1renderer_1_1_font" ],
    [ "font_description", "d4/d2e/structopenage_1_1renderer_1_1font__description.xhtml", "d4/d2e/structopenage_1_1renderer_1_1font__description" ],
    [ "FontManager", "d9/d2e/classopenage_1_1renderer_1_1_font_manager.xhtml", "d9/d2e/classopenage_1_1renderer_1_1_font_manager" ],
    [ "FreeTypeLibrary", "d5/da5/classopenage_1_1renderer_1_1_free_type_library.xhtml", "d5/da5/classopenage_1_1renderer_1_1_free_type_library" ],
    [ "Geometry", "d2/d58/classopenage_1_1renderer_1_1_geometry.xhtml", "d2/d58/classopenage_1_1renderer_1_1_geometry" ],
    [ "Glyph", "d1/d33/classopenage_1_1renderer_1_1_glyph.xhtml", "d1/d33/classopenage_1_1renderer_1_1_glyph" ],
    [ "GlyphAtlas", "d4/d54/classopenage_1_1renderer_1_1_glyph_atlas.xhtml", "d4/d54/classopenage_1_1renderer_1_1_glyph_atlas" ],
    [ "Renderable", "d3/d60/structopenage_1_1renderer_1_1_renderable.xhtml", "d3/d60/structopenage_1_1renderer_1_1_renderable" ],
    [ "Renderer", "d3/d39/classopenage_1_1renderer_1_1_renderer.xhtml", "d3/d39/classopenage_1_1renderer_1_1_renderer" ],
    [ "RenderPass", "d2/dbb/structopenage_1_1renderer_1_1_render_pass.xhtml", "d2/dbb/structopenage_1_1renderer_1_1_render_pass" ],
    [ "RenderTarget", "d0/da1/classopenage_1_1renderer_1_1_render_target.xhtml", "d0/da1/classopenage_1_1renderer_1_1_render_target" ],
    [ "SDL", "d3/ddf/classopenage_1_1renderer_1_1_s_d_l.xhtml", "d3/ddf/classopenage_1_1renderer_1_1_s_d_l" ],
    [ "ShaderProgram", "d7/d3c/classopenage_1_1renderer_1_1_shader_program.xhtml", "d7/d3c/classopenage_1_1renderer_1_1_shader_program" ],
    [ "text_render_task", "d3/deb/structopenage_1_1renderer_1_1text__render__task.xhtml", "d3/deb/structopenage_1_1renderer_1_1text__render__task" ],
    [ "text_render_vertex", "d1/deb/structopenage_1_1renderer_1_1text__render__vertex.xhtml", "d1/deb/structopenage_1_1renderer_1_1text__render__vertex" ],
    [ "TextRenderer", "d4/dba/classopenage_1_1renderer_1_1_text_renderer.xhtml", "d4/dba/classopenage_1_1renderer_1_1_text_renderer" ],
    [ "Texture2d", "de/dcc/classopenage_1_1renderer_1_1_texture2d.xhtml", "de/dcc/classopenage_1_1renderer_1_1_texture2d" ],
    [ "Texture2dArray", "de/d5c/classopenage_1_1renderer_1_1_texture2d_array.xhtml", "de/d5c/classopenage_1_1renderer_1_1_texture2d_array" ],
    [ "UniformInput", "d6/def/classopenage_1_1renderer_1_1_uniform_input.xhtml", "d6/def/classopenage_1_1renderer_1_1_uniform_input" ],
    [ "Window", "d0/de5/classopenage_1_1renderer_1_1_window.xhtml", "d0/de5/classopenage_1_1renderer_1_1_window" ]
];