openage::input::Event
const ClassCode openage::input::Event::cc
Referenced by as_char, openage::Engine::Engine, openage::input::InputContext::execute_if_bound, openage::input::InputManager::ignored, info, openage::input::InputManager::InputManager, openage::input::InputManager::key_bind_to_string, openage::input::InputManager::mouse_bind_to_string, openage::ActionMode::on_game_control_set, openage::EditorMode::on_game_control_set, openage::input::event_hash::operator(), operator==, openage::input::InputManager::set_state, openage::input::InputManager::wheel_bind_to_string.
const modset_t openage::input::Event::mod
Referenced by info, openage::input::InputManager::InputManager, openage::input::InputManager::key_bind_to_string, operator==, openage::input::InputManager::set_state.
const std::string openage::input::Event::utf8
Referenced by as_utf8, operator==.
openage::input::Event::Event(event_class cl, code_t code, modset_t mod)
Referenced by openage::input::sdl_key, openage::input::sdl_mouse, openage::input::sdl_mouse_up_down, openage::input::sdl_wheel, openage::input::utf8.
openage::input::Event::Event(event_class cl, const std::string &, modset_t mod)
char openage::input::Event::as_char() const
Return keyboard text as char returns 0 for non-text events.
References cc, openage::input::ClassCode::code.
Referenced by info, openage::console::Console::register_to_engine.
std::string openage::input::Event::as_utf8() const
Returns a utf encoded char or an empty string for non-utf8 events.
References utf8.
Referenced by openage::input::InputManager::InputManager, openage::console::Console::register_to_engine.
std::string openage::input::Event::info() const
logable debug info
References as_char, cc, openage::input::ClassCode::code, openage::input::ClassCode::eclass, mod, openage.testing.testing.result, std::to_string.
bool openage::input::Event::operator==(const Event &other) const
References cc, mod, utf8.