openage::UngarrisonAction
coord::phys3 openage::UngarrisonAction::position
Referenced by UngarrisonAction.
bool openage::UngarrisonAction::complete
Referenced by UngarrisonAction.
openage::UngarrisonAction::UngarrisonAction(Unit *e, const coord::phys3 &pos)
References complete, position, openage::standing.
virtual openage::UngarrisonAction::~UngarrisonAction()
References openage::IntervalTimer::update.
void openage::UngarrisonAction::update(unsigned int time) override
each action has its own update functionality which gets called when this is the active action
References openage::UnitAction::entity, openage::garrison, openage::Unit::get_attribute.
void openage::UngarrisonAction::on_completion() override
action to perform when popped from a units action stack
bool openage::UngarrisonAction::completed() const override
gets called for all actions on stack each update cycle
true when action is completed so it and everything above it can be popped
bool openage::UngarrisonAction::allow_interrupt() const override
checks if the action can be interrupted, allowing it to be popped if the user specifies a new action, if false the action must reach a completed state before removal eg dead action must be completed and cannot be discarded
bool openage::UngarrisonAction::allow_control() const override
control whether stack can discard the action automatically and should the stack be modifiable when this action is on top
if true this action must complete and will not allow new actions to be pushed while it is active and also does not update the secondary actions
std::string openage::UngarrisonAction::name() const override
debug string to identify action types
Referenced by openage.util.fslike.path.Path.stem, openage.util.fslike.path.Path.suffix, openage.util.fslike.path.Path.suffixes.