var namespaceopenage =
[
    [ "__main__", "dd/dea/namespaceopenage_1_1____main____.xhtml", "dd/dea/namespaceopenage_1_1____main____" ],
    [ "audio", "d5/d78/namespaceopenage_1_1audio.xhtml", "d5/d78/namespaceopenage_1_1audio" ],
    [ "cabextract", "db/d4e/namespaceopenage_1_1cabextract.xhtml", "db/d4e/namespaceopenage_1_1cabextract" ],
    [ "codegen", "d9/dd4/namespaceopenage_1_1codegen.xhtml", "d9/dd4/namespaceopenage_1_1codegen" ],
    [ "console", "dd/d31/namespaceopenage_1_1console.xhtml", "dd/d31/namespaceopenage_1_1console" ],
    [ "convert", "d2/d78/namespaceopenage_1_1convert.xhtml", "d2/d78/namespaceopenage_1_1convert" ],
    [ "coord", "d1/d93/namespaceopenage_1_1coord.xhtml", "d1/d93/namespaceopenage_1_1coord" ],
    [ "cppinterface", "d4/d97/namespaceopenage_1_1cppinterface.xhtml", null ],
    [ "curve", "df/dbd/namespaceopenage_1_1curve.xhtml", "df/dbd/namespaceopenage_1_1curve" ],
    [ "cvar", "da/dc9/namespaceopenage_1_1cvar.xhtml", "da/dc9/namespaceopenage_1_1cvar" ],
    [ "datastructure", "d2/d4a/namespaceopenage_1_1datastructure.xhtml", "d2/d4a/namespaceopenage_1_1datastructure" ],
    [ "error", "db/dbd/namespaceopenage_1_1error.xhtml", "db/dbd/namespaceopenage_1_1error" ],
    [ "event", "d6/dc6/namespaceopenage_1_1event.xhtml", "d6/dc6/namespaceopenage_1_1event" ],
    [ "game", "d3/d1a/namespaceopenage_1_1game.xhtml", null ],
    [ "gui", "d3/d8f/namespaceopenage_1_1gui.xhtml", "d3/d8f/namespaceopenage_1_1gui" ],
    [ "input", "d5/dc6/namespaceopenage_1_1input.xhtml", "d5/dc6/namespaceopenage_1_1input" ],
    [ "job", "d6/d74/namespaceopenage_1_1job.xhtml", "d6/d74/namespaceopenage_1_1job" ],
    [ "log", "dd/d1a/namespaceopenage_1_1log.xhtml", "dd/d1a/namespaceopenage_1_1log" ],
    [ "options", "db/da7/namespaceopenage_1_1options.xhtml", "db/da7/namespaceopenage_1_1options" ],
    [ "path", "d3/df4/namespaceopenage_1_1path.xhtml", "d3/df4/namespaceopenage_1_1path" ],
    [ "pyinterface", "d9/dde/namespaceopenage_1_1pyinterface.xhtml", "d9/dde/namespaceopenage_1_1pyinterface" ],
    [ "renderer", "d3/db5/namespaceopenage_1_1renderer.xhtml", "d3/db5/namespaceopenage_1_1renderer" ],
    [ "rng", "d8/d88/namespaceopenage_1_1rng.xhtml", "d8/d88/namespaceopenage_1_1rng" ],
    [ "shader", "dc/da0/namespaceopenage_1_1shader.xhtml", "dc/da0/namespaceopenage_1_1shader" ],
    [ "testing", "d3/d82/namespaceopenage_1_1testing.xhtml", "d3/d82/namespaceopenage_1_1testing" ],
    [ "util", "de/d60/namespaceopenage_1_1util.xhtml", "de/d60/namespaceopenage_1_1util" ],
    [ "ActionMode", "d8/d06/classopenage_1_1_action_mode.xhtml", "d8/d06/classopenage_1_1_action_mode" ],
    [ "ActionModeSignals", "d8/de3/classopenage_1_1_action_mode_signals.xhtml", "d8/de3/classopenage_1_1_action_mode_signals" ],
    [ "AssetManager", "d4/dbb/classopenage_1_1_asset_manager.xhtml", "d4/dbb/classopenage_1_1_asset_manager" ],
    [ "AttackAbility", "d8/d36/classopenage_1_1_attack_ability.xhtml", "d8/d36/classopenage_1_1_attack_ability" ],
    [ "AttackAction", "d7/d12/classopenage_1_1_attack_action.xhtml", "d7/d12/classopenage_1_1_attack_action" ],
    [ "Attribute", "d2/d22/classopenage_1_1_attribute.xhtml", null ],
    [ "Attribute< attr_type::armor >", "da/d33/classopenage_1_1_attribute_3_01attr__type_1_1armor_01_4.xhtml", "da/d33/classopenage_1_1_attribute_3_01attr__type_1_1armor_01_4" ],
    [ "Attribute< attr_type::attack >", "de/dd0/classopenage_1_1_attribute_3_01attr__type_1_1attack_01_4.xhtml", "de/dd0/classopenage_1_1_attribute_3_01attr__type_1_1attack_01_4" ],
    [ "Attribute< attr_type::building >", "d3/d37/classopenage_1_1_attribute_3_01attr__type_1_1building_01_4.xhtml", "d3/d37/classopenage_1_1_attribute_3_01attr__type_1_1building_01_4" ],
    [ "Attribute< attr_type::damaged >", "d3/dd9/classopenage_1_1_attribute_3_01attr__type_1_1damaged_01_4.xhtml", "d3/dd9/classopenage_1_1_attribute_3_01attr__type_1_1damaged_01_4" ],
    [ "Attribute< attr_type::direction >", "df/d07/classopenage_1_1_attribute_3_01attr__type_1_1direction_01_4.xhtml", "df/d07/classopenage_1_1_attribute_3_01attr__type_1_1direction_01_4" ],
    [ "Attribute< attr_type::dropsite >", "df/dca/classopenage_1_1_attribute_3_01attr__type_1_1dropsite_01_4.xhtml", "df/dca/classopenage_1_1_attribute_3_01attr__type_1_1dropsite_01_4" ],
    [ "Attribute< attr_type::formation >", "d9/d88/classopenage_1_1_attribute_3_01attr__type_1_1formation_01_4.xhtml", "d9/d88/classopenage_1_1_attribute_3_01attr__type_1_1formation_01_4" ],
    [ "Attribute< attr_type::garrison >", "d2/db8/classopenage_1_1_attribute_3_01attr__type_1_1garrison_01_4.xhtml", "d2/db8/classopenage_1_1_attribute_3_01attr__type_1_1garrison_01_4" ],
    [ "Attribute< attr_type::heal >", "d0/d7f/classopenage_1_1_attribute_3_01attr__type_1_1heal_01_4.xhtml", "d0/d7f/classopenage_1_1_attribute_3_01attr__type_1_1heal_01_4" ],
    [ "Attribute< attr_type::hitpoints >", "d8/d1a/classopenage_1_1_attribute_3_01attr__type_1_1hitpoints_01_4.xhtml", "d8/d1a/classopenage_1_1_attribute_3_01attr__type_1_1hitpoints_01_4" ],
    [ "Attribute< attr_type::multitype >", "d3/da7/classopenage_1_1_attribute_3_01attr__type_1_1multitype_01_4.xhtml", "d3/da7/classopenage_1_1_attribute_3_01attr__type_1_1multitype_01_4" ],
    [ "Attribute< attr_type::owner >", "d4/d01/classopenage_1_1_attribute_3_01attr__type_1_1owner_01_4.xhtml", "d4/d01/classopenage_1_1_attribute_3_01attr__type_1_1owner_01_4" ],
    [ "Attribute< attr_type::population >", "df/d6b/classopenage_1_1_attribute_3_01attr__type_1_1population_01_4.xhtml", "df/d6b/classopenage_1_1_attribute_3_01attr__type_1_1population_01_4" ],
    [ "Attribute< attr_type::projectile >", "d7/d9e/classopenage_1_1_attribute_3_01attr__type_1_1projectile_01_4.xhtml", "d7/d9e/classopenage_1_1_attribute_3_01attr__type_1_1projectile_01_4" ],
    [ "Attribute< attr_type::resource >", "de/d9b/classopenage_1_1_attribute_3_01attr__type_1_1resource_01_4.xhtml", "de/d9b/classopenage_1_1_attribute_3_01attr__type_1_1resource_01_4" ],
    [ "Attribute< attr_type::resource_generator >", "d1/d72/classopenage_1_1_attribute_3_01attr__type_1_1resource__generator_01_4.xhtml", "d1/d72/classopenage_1_1_attribute_3_01attr__type_1_1resource__generator_01_4" ],
    [ "Attribute< attr_type::speed >", "de/d8c/classopenage_1_1_attribute_3_01attr__type_1_1speed_01_4.xhtml", "de/d8c/classopenage_1_1_attribute_3_01attr__type_1_1speed_01_4" ],
    [ "Attribute< attr_type::storage >", "d5/d62/classopenage_1_1_attribute_3_01attr__type_1_1storage_01_4.xhtml", "d5/d62/classopenage_1_1_attribute_3_01attr__type_1_1storage_01_4" ],
    [ "Attribute< attr_type::worker >", "dd/d31/classopenage_1_1_attribute_3_01attr__type_1_1worker_01_4.xhtml", "dd/d31/classopenage_1_1_attribute_3_01attr__type_1_1worker_01_4" ],
    [ "AttributeContainer", "df/d4d/classopenage_1_1_attribute_container.xhtml", "df/d4d/classopenage_1_1_attribute_container" ],
    [ "Attributes", "de/d8a/classopenage_1_1_attributes.xhtml", "de/d8a/classopenage_1_1_attributes" ],
    [ "BuildAbility", "d2/dbc/classopenage_1_1_build_ability.xhtml", "d2/dbc/classopenage_1_1_build_ability" ],
    [ "BuildAction", "d6/dc0/classopenage_1_1_build_action.xhtml", "d6/dc0/classopenage_1_1_build_action" ],
    [ "BuildingProducer", "d4/d85/classopenage_1_1_building_producer.xhtml", "d4/d85/classopenage_1_1_building_producer" ],
    [ "chunk_neighbors", "d8/d91/structopenage_1_1chunk__neighbors.xhtml", "d8/d91/structopenage_1_1chunk__neighbors" ],
    [ "Civilisation", "de/d7a/classopenage_1_1_civilisation.xhtml", "de/d7a/classopenage_1_1_civilisation" ],
    [ "ClassicResources", "dc/ddf/classopenage_1_1_classic_resources.xhtml", "dc/ddf/classopenage_1_1_classic_resources" ],
    [ "Command", "d8/dda/classopenage_1_1_command.xhtml", "d8/dda/classopenage_1_1_command" ],
    [ "ConvertAbility", "df/d28/classopenage_1_1_convert_ability.xhtml", "df/d28/classopenage_1_1_convert_ability" ],
    [ "ConvertAction", "d9/d5d/classopenage_1_1_convert_action.xhtml", "d9/d5d/classopenage_1_1_convert_action" ],
    [ "coord_chunk_hash", "d7/dca/structopenage_1_1coord__chunk__hash.xhtml", "d7/dca/structopenage_1_1coord__chunk__hash" ],
    [ "CreateMode", "d3/d4b/classopenage_1_1_create_mode.xhtml", "d3/d4b/classopenage_1_1_create_mode" ],
    [ "DeadAction", "df/d52/classopenage_1_1_dead_action.xhtml", "df/d52/classopenage_1_1_dead_action" ],
    [ "DecayAction", "d6/dd7/classopenage_1_1_decay_action.xhtml", "d6/dd7/classopenage_1_1_decay_action" ],
    [ "DrawHandler", "d3/dbd/classopenage_1_1_draw_handler.xhtml", "d3/dbd/classopenage_1_1_draw_handler" ],
    [ "EditorMode", "db/d42/classopenage_1_1_editor_mode.xhtml", "db/d42/classopenage_1_1_editor_mode" ],
    [ "EditorModeSignals", "db/dd6/classopenage_1_1_editor_mode_signals.xhtml", "db/dd6/classopenage_1_1_editor_mode_signals" ],
    [ "Engine", "d6/d40/classopenage_1_1_engine.xhtml", "d6/d40/classopenage_1_1_engine" ],
    [ "EngineSignals", "de/dbb/classopenage_1_1_engine_signals.xhtml", "de/dbb/classopenage_1_1_engine_signals" ],
    [ "FoundationAction", "d4/d40/classopenage_1_1_foundation_action.xhtml", "d4/d40/classopenage_1_1_foundation_action" ],
    [ "GameControl", "d8/db5/classopenage_1_1_game_control.xhtml", "d8/db5/classopenage_1_1_game_control" ],
    [ "GameControlSignals", "d9/d8d/classopenage_1_1_game_control_signals.xhtml", "d9/d8d/classopenage_1_1_game_control_signals" ],
    [ "GameMain", "d9/d9c/classopenage_1_1_game_main.xhtml", "d9/d9c/classopenage_1_1_game_main" ],
    [ "GameMainHandle", "d0/dd5/classopenage_1_1_game_main_handle.xhtml", "d0/dd5/classopenage_1_1_game_main_handle" ],
    [ "GameMainSignals", "de/dfe/classopenage_1_1_game_main_signals.xhtml", "de/dfe/classopenage_1_1_game_main_signals" ],
    [ "GameRenderer", "d3/d7e/classopenage_1_1_game_renderer.xhtml", "d3/d7e/classopenage_1_1_game_renderer" ],
    [ "GameSpec", "de/d6a/classopenage_1_1_game_spec.xhtml", "de/d6a/classopenage_1_1_game_spec" ],
    [ "GameSpecHandle", "d7/de7/classopenage_1_1_game_spec_handle.xhtml", "d7/de7/classopenage_1_1_game_spec_handle" ],
    [ "GameSpecSignals", "da/dde/classopenage_1_1_game_spec_signals.xhtml", "da/dde/classopenage_1_1_game_spec_signals" ],
    [ "GarrisonAbility", "d3/dea/classopenage_1_1_garrison_ability.xhtml", "d3/dea/classopenage_1_1_garrison_ability" ],
    [ "GarrisonAction", "d3/d9d/classopenage_1_1_garrison_action.xhtml", "d3/d9d/classopenage_1_1_garrison_action" ],
    [ "GatherAbility", "d0/d1c/classopenage_1_1_gather_ability.xhtml", "d0/d1c/classopenage_1_1_gather_ability" ],
    [ "GatherAction", "db/d43/classopenage_1_1_gather_action.xhtml", "db/d43/classopenage_1_1_gather_action" ],
    [ "Generator", "dd/d78/classopenage_1_1_generator.xhtml", "dd/d78/classopenage_1_1_generator" ],
    [ "gl_texture_buffer", "d4/d27/structopenage_1_1gl__texture__buffer.xhtml", "d4/d27/structopenage_1_1gl__texture__buffer" ],
    [ "HealAbility", "d4/d30/classopenage_1_1_heal_ability.xhtml", "d4/d30/classopenage_1_1_heal_ability" ],
    [ "HealAction", "d9/deb/classopenage_1_1_heal_action.xhtml", "d9/deb/classopenage_1_1_heal_action" ],
    [ "HudHandler", "dd/dba/classopenage_1_1_hud_handler.xhtml", "dd/dba/classopenage_1_1_hud_handler" ],
    [ "IdleAction", "da/dd8/classopenage_1_1_idle_action.xhtml", "da/dd8/classopenage_1_1_idle_action" ],
    [ "influence", "d6/d08/structopenage_1_1influence.xhtml", "d6/d08/structopenage_1_1influence" ],
    [ "influence_group", "d9/d65/structopenage_1_1influence__group.xhtml", "d9/d65/structopenage_1_1influence__group" ],
    [ "InputHandler", "da/dc5/classopenage_1_1_input_handler.xhtml", "da/dc5/classopenage_1_1_input_handler" ],
    [ "IntervalTimer", "de/d24/classopenage_1_1_interval_timer.xhtml", "de/d24/classopenage_1_1_interval_timer" ],
    [ "LivingProducer", "db/db1/classopenage_1_1_living_producer.xhtml", "db/db1/classopenage_1_1_living_producer" ],
    [ "main_arguments", "de/d05/structopenage_1_1main__arguments.xhtml", "de/d05/structopenage_1_1main__arguments" ],
    [ "Market", "d1/dae/classopenage_1_1_market.xhtml", "d1/dae/classopenage_1_1_market" ],
    [ "MovableProducer", "de/d30/classopenage_1_1_movable_producer.xhtml", "de/d30/classopenage_1_1_movable_producer" ],
    [ "MoveAbility", "de/d53/classopenage_1_1_move_ability.xhtml", "de/d53/classopenage_1_1_move_ability" ],
    [ "MoveAction", "d2/d4e/classopenage_1_1_move_action.xhtml", "d2/d4e/classopenage_1_1_move_action" ],
    [ "neighbor_tile", "d7/d21/structopenage_1_1neighbor__tile.xhtml", "d7/d21/structopenage_1_1neighbor__tile" ],
    [ "NyanResearchType", "d0/d04/classopenage_1_1_nyan_research_type.xhtml", "d0/d04/classopenage_1_1_nyan_research_type" ],
    [ "NyanType", "dc/dfe/classopenage_1_1_nyan_type.xhtml", "dc/dfe/classopenage_1_1_nyan_type" ],
    [ "ObjectProducer", "d2/d60/classopenage_1_1_object_producer.xhtml", "d2/d60/classopenage_1_1_object_producer" ],
    [ "OutputMode", "de/d24/classopenage_1_1_output_mode.xhtml", "de/d24/classopenage_1_1_output_mode" ],
    [ "OutputModeSignals", "d3/d93/classopenage_1_1_output_mode_signals.xhtml", "d3/d93/classopenage_1_1_output_mode_signals" ],
    [ "PatrolAbility", "de/d88/classopenage_1_1_patrol_ability.xhtml", "de/d88/classopenage_1_1_patrol_ability" ],
    [ "Player", "d8/d47/classopenage_1_1_player.xhtml", "d8/d47/classopenage_1_1_player" ],
    [ "PlayerScore", "d8/de3/classopenage_1_1_player_score.xhtml", "d8/de3/classopenage_1_1_player_score" ],
    [ "PopulationTracker", "dd/d70/classopenage_1_1_population_tracker.xhtml", "dd/d70/classopenage_1_1_population_tracker" ],
    [ "ProjectileAction", "d5/d14/classopenage_1_1_projectile_action.xhtml", "d5/d14/classopenage_1_1_projectile_action" ],
    [ "ProjectileProducer", "df/d00/classopenage_1_1_projectile_producer.xhtml", "df/d00/classopenage_1_1_projectile_producer" ],
    [ "RadialObject", "d6/d31/classopenage_1_1_radial_object.xhtml", "d6/d31/classopenage_1_1_radial_object" ],
    [ "reference_data", "d9/d67/structopenage_1_1reference__data.xhtml", "d9/d67/structopenage_1_1reference__data" ],
    [ "Region", "d1/d80/classopenage_1_1_region.xhtml", "d1/d80/classopenage_1_1_region" ],
    [ "RenderOptions", "dd/df6/classopenage_1_1_render_options.xhtml", "dd/df6/classopenage_1_1_render_options" ],
    [ "RepairAbility", "dd/d47/classopenage_1_1_repair_ability.xhtml", "dd/d47/classopenage_1_1_repair_ability" ],
    [ "RepairAction", "db/da0/classopenage_1_1_repair_action.xhtml", "db/da0/classopenage_1_1_repair_action" ],
    [ "Research", "db/d44/classopenage_1_1_research.xhtml", "db/d44/classopenage_1_1_research" ],
    [ "ResearchAbility", "d0/d91/classopenage_1_1_research_ability.xhtml", "d0/d91/classopenage_1_1_research_ability" ],
    [ "ResearchAction", "d2/d44/classopenage_1_1_research_action.xhtml", "d2/d44/classopenage_1_1_research_action" ],
    [ "ResearchType", "d2/d89/classopenage_1_1_research_type.xhtml", "d2/d89/classopenage_1_1_research_type" ],
    [ "ResizeHandler", "db/d8a/classopenage_1_1_resize_handler.xhtml", "db/d8a/classopenage_1_1_resize_handler" ],
    [ "Resource", "de/da8/classopenage_1_1_resource.xhtml", "de/da8/classopenage_1_1_resource" ],
    [ "ResourceBundle", "d2/de9/classopenage_1_1_resource_bundle.xhtml", "d2/de9/classopenage_1_1_resource_bundle" ],
    [ "ResourceCost", "d8/d5b/classopenage_1_1_resource_cost.xhtml", "d8/d5b/classopenage_1_1_resource_cost" ],
    [ "ResourceProducer", "df/dce/classopenage_1_1_resource_producer.xhtml", "df/dce/classopenage_1_1_resource_producer" ],
    [ "Resources", "d7/dcf/classopenage_1_1_resources.xhtml", "d7/dcf/classopenage_1_1_resources" ],
    [ "Score", "d8/dd7/classopenage_1_1_score.xhtml", "d8/dd7/classopenage_1_1_score" ],
    [ "ScreenshotManager", "d5/dfd/classopenage_1_1_screenshot_manager.xhtml", "d5/dfd/classopenage_1_1_screenshot_manager" ],
    [ "SetPointAbility", "d1/d1b/classopenage_1_1_set_point_ability.xhtml", "d1/d1b/classopenage_1_1_set_point_ability" ],
    [ "SharedAttributeContainer", "d4/d90/classopenage_1_1_shared_attribute_container.xhtml", "d4/d90/classopenage_1_1_shared_attribute_container" ],
    [ "Sound", "d6/d57/classopenage_1_1_sound.xhtml", "d6/d57/classopenage_1_1_sound" ],
    [ "SquareObject", "d0/dcc/classopenage_1_1_square_object.xhtml", "d0/dcc/classopenage_1_1_square_object" ],
    [ "TargetAction", "d6/ddd/classopenage_1_1_target_action.xhtml", "d6/ddd/classopenage_1_1_target_action" ],
    [ "Team", "de/dfb/classopenage_1_1_team.xhtml", "de/dfb/classopenage_1_1_team" ],
    [ "TeamScore", "d4/db7/classopenage_1_1_team_score.xhtml", "d4/db7/classopenage_1_1_team_score" ],
    [ "Terrain", "d4/d15/classopenage_1_1_terrain.xhtml", "d4/d15/classopenage_1_1_terrain" ],
    [ "terrain_meta", "d3/dcb/structopenage_1_1terrain__meta.xhtml", "d3/dcb/structopenage_1_1terrain__meta" ],
    [ "terrain_render_data", "d1/daf/structopenage_1_1terrain__render__data.xhtml", "d1/daf/structopenage_1_1terrain__render__data" ],
    [ "TerrainChunk", "d9/dab/classopenage_1_1_terrain_chunk.xhtml", "d9/dab/classopenage_1_1_terrain_chunk" ],
    [ "TerrainObject", "db/db3/classopenage_1_1_terrain_object.xhtml", "db/db3/classopenage_1_1_terrain_object" ],
    [ "TerrainSearch", "d0/dee/classopenage_1_1_terrain_search.xhtml", "d0/dee/classopenage_1_1_terrain_search" ],
    [ "Texture", "d4/d5b/classopenage_1_1_texture.xhtml", "d4/d5b/classopenage_1_1_texture" ],
    [ "TickHandler", "d1/da0/classopenage_1_1_tick_handler.xhtml", "d1/da0/classopenage_1_1_tick_handler" ],
    [ "tile_data", "db/dde/structopenage_1_1tile__data.xhtml", "db/dde/structopenage_1_1tile__data" ],
    [ "tile_draw_data", "d7/d14/structopenage_1_1tile__draw__data.xhtml", "d7/d14/structopenage_1_1tile__draw__data" ],
    [ "tile_range", "d6/de8/structopenage_1_1tile__range.xhtml", "d6/de8/structopenage_1_1tile__range" ],
    [ "TileContent", "d3/dd0/classopenage_1_1_tile_content.xhtml", "d3/dd0/classopenage_1_1_tile_content" ],
    [ "TrainAbility", "d5/d34/classopenage_1_1_train_ability.xhtml", "d5/d34/classopenage_1_1_train_ability" ],
    [ "TrainAction", "d5/d62/classopenage_1_1_train_action.xhtml", "d5/d62/classopenage_1_1_train_action" ],
    [ "TypePair", "dd/d1d/classopenage_1_1_type_pair.xhtml", "dd/d1d/classopenage_1_1_type_pair" ],
    [ "UngarrisonAbility", "df/d01/classopenage_1_1_ungarrison_ability.xhtml", "df/d01/classopenage_1_1_ungarrison_ability" ],
    [ "UngarrisonAction", "d6/d81/classopenage_1_1_ungarrison_action.xhtml", "d6/d81/classopenage_1_1_ungarrison_action" ],
    [ "Unit", "df/dea/classopenage_1_1_unit.xhtml", "df/dea/classopenage_1_1_unit" ],
    [ "UnitAbility", "d3/d44/classopenage_1_1_unit_ability.xhtml", "d3/d44/classopenage_1_1_unit_ability" ],
    [ "UnitAction", "dc/d74/classopenage_1_1_unit_action.xhtml", "dc/d74/classopenage_1_1_unit_action" ],
    [ "UnitContainer", "d2/d82/classopenage_1_1_unit_container.xhtml", "d2/d82/classopenage_1_1_unit_container" ],
    [ "UnitReference", "d3/d37/classopenage_1_1_unit_reference.xhtml", "d3/d37/classopenage_1_1_unit_reference" ],
    [ "UnitSelection", "d9/de2/classopenage_1_1_unit_selection.xhtml", "d9/de2/classopenage_1_1_unit_selection" ],
    [ "UnitTexture", "d9/d0c/classopenage_1_1_unit_texture.xhtml", "d9/d0c/classopenage_1_1_unit_texture" ],
    [ "UnitType", "dd/d39/classopenage_1_1_unit_type.xhtml", "dd/d39/classopenage_1_1_unit_type" ],
    [ "UnitTypeMeta", "d3/d6c/classopenage_1_1_unit_type_meta.xhtml", "d3/d6c/classopenage_1_1_unit_type_meta" ],
    [ "UnsharedAttributeContainer", "d8/d3c/classopenage_1_1_unshared_attribute_container.xhtml", "d8/d3c/classopenage_1_1_unshared_attribute_container" ]
];