openage::input::ClassCode
const event_class openage::input::ClassCode::eclass
Referenced by get_classes, openage::input::Event::info, openage::input::InputManager::InputManager, openage::input::class_code_hash::operator(), openage::input::operator==.
const code_t openage::input::ClassCode::code
Referenced by openage::input::Event::as_char, openage::input::Event::info, openage::input::InputManager::InputManager, openage::input::InputManager::key_bind_to_string, openage::input::InputManager::mouse_bind_to_string, openage::input::class_code_hash::operator(), openage::input::operator==, openage::input::InputManager::wheel_bind_to_string.
openage::input::ClassCode::ClassCode(event_class cl, code_t code)
std::vector< event_class > openage::input::ClassCode::get_classes() const
classes ordered with most specific first
References eclass, openage::input::event_base, openage.testing.testing.result.
Referenced by openage::input::InputContext::execute_if_bound, has_class.
bool openage::input::ClassCode::has_class(const event_class &c) const
References get_classes.
Referenced by openage::Engine::Engine, openage::input::InputManager::ignored.