qtsdl::GuiRenderingSetupRoutines
friend class GuiRenderingCtxActivator
std::unique_ptr<CtxExtractionMode> qtsdl::GuiRenderingSetupRoutines::ctx_extraction_mode
Referenced by get_ctx, GuiRenderingSetupRoutines, post_render, pre_render.
qtsdl::GuiRenderingSetupRoutines::GuiRenderingSetupRoutines(SDL_Window *window)
References ctx_extraction_mode.
qtsdl::GuiRenderingSetupRoutines::~GuiRenderingSetupRoutines()
QOpenGLContext * qtsdl::GuiRenderingSetupRoutines::get_ctx()
References ctx_extraction_mode.
Referenced by qtsdl::GuiRendererImpl::GuiRendererImpl, qtsdl::GuiRendererImpl::reinit_fbo_if_needed.
void qtsdl::GuiRenderingSetupRoutines::pre_render()
References ctx_extraction_mode.
Referenced by qtsdl::GuiRenderingCtxActivator::GuiRenderingCtxActivator.
void qtsdl::GuiRenderingSetupRoutines::post_render()
References ctx_extraction_mode.
Referenced by qtsdl::GuiRenderingCtxActivator::~GuiRenderingCtxActivator.