openage::EditorModeSignals
EditorMode* openage::EditorModeSignals::editor_mode
Referenced by on_current_player_name_changed.
openage::EditorModeSignals::EditorModeSignals(EditorMode *editor_mode)
void openage::EditorModeSignals::on_current_player_name_changed()
References openage::EditorMode::announce_categories, editor_mode.
Referenced by openage::EditorMode::set_game_control.
void openage::EditorModeSignals::toggle()
Referenced by openage::EditorMode::on_game_control_set.
void openage::EditorModeSignals::categories_changed(const std::vector< std::string > &categories)
Referenced by openage::EditorMode::announce_categories.
void openage::EditorModeSignals::categories_content_changed()
Referenced by openage::EditorMode::announce_categories.
void openage::EditorModeSignals::category_content_changed(const std::string &category_name, std::vector< std::tuple< index_t, uint16_t >> &type_and_texture)
Referenced by openage::EditorMode::announce_category_content.