openage::gui::ActionModeLink
QString openage::gui::ActionModeLink::ability
QString openage::gui::ActionModeLink::population
bool openage::gui::ActionModeLink::population_warn
int openage::gui::ActionModeLink::selection_size
QString openage::gui::ActionModeLink::selection_name
QString openage::gui::ActionModeLink::selection_icon
QString openage::gui::ActionModeLink::selection_type
QString openage::gui::ActionModeLink::selection_owner
QString openage::gui::ActionModeLink::selection_hp
QString openage::gui::ActionModeLink::selection_attrs
const UnitSelection* openage::gui::ActionModeLink::selection
openage::gui::ActionModeLink::ActionModeLink(QObject *parent=nullptr)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
virtual openage::gui::ActionModeLink::~ActionModeLink()
Referenced by openage::gui::OutputModeLink::OutputModeLink.
QString openage::gui::ActionModeLink::get_ability() const
Referenced by openage::gui::OutputModeLink::OutputModeLink.
QString openage::gui::ActionModeLink::get_population() const
Referenced by openage::gui::OutputModeLink::OutputModeLink.
bool openage::gui::ActionModeLink::get_population_warn() const
Referenced by openage::gui::OutputModeLink::OutputModeLink.
int openage::gui::ActionModeLink::get_selection_size() const
Referenced by openage::gui::OutputModeLink::OutputModeLink.
Q_INVOKABLE void openage::gui::ActionModeLink::act(const QString &action)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
void openage::gui::ActionModeLink::ability_changed()
void openage::gui::ActionModeLink::action_triggered(const std::string &ability)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
void openage::gui::ActionModeLink::buttons_type_changed(const ActionButtonsType buttons_type)
Referenced by openage::gui::ActionsListModel::set_action_mode.
void openage::gui::ActionModeLink::population_changed()
void openage::gui::ActionModeLink::selection_changed()
void openage::gui::ActionModeLink::on_ability_changed(const std::string &ability)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
void openage::gui::ActionModeLink::on_buttons_type_changed(const ActionButtonsType buttons_type)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
void openage::gui::ActionModeLink::on_population_changed(int demand, int capacity, bool warn)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
void openage::gui::ActionModeLink::on_selection_changed(const UnitSelection *unit_selection, const Player *player)
Referenced by openage::gui::OutputModeLink::OutputModeLink.
virtual void openage::gui::ActionModeLink::on_core_adopted() override
Referenced by openage::gui::OutputModeLink::OutputModeLink.
std::string openage::gui::ActionModeLink::progress(float progress, int size)
Referenced by openage::gui::OutputModeLink::OutputModeLink.