openage::util::StringFormatter
std::string* openage::util::StringFormatter< ChildType >::output
Referenced by openage::util::StringFormatter< Formatter >::operator=.
CachableOSStream* openage::util::StringFormatter< ChildType >::stream_ptr
openage::util::StringFormatter< ChildType >::StringFormatter(std::string &output)
buffer All input data is appended to this object.
virtual openage::util::StringFormatter< ChildType >::~StringFormatter()
Releases the CachableOSStream object (if it was acquired).
ChildType& openage::util::StringFormatter< ChildType >::child_type_ref()
openage::util::StringFormatter< ChildType >::StringFormatter(StringFormatter< ChildType > &&other) noexcept
StringFormatter<ChildType>& openage::util::StringFormatter< ChildType >::operator=(StringFormatter< ChildType > &&other) noexcept
openage::util::StringFormatter< ChildType >::StringFormatter(const StringFormatter &)=delete
StringFormatter& openage::util::StringFormatter< ChildType >::operator=(const StringFormatter &)=delete
ChildType& openage::util::StringFormatter< ChildType >::operator<<(const T &t)
ChildType& openage::util::StringFormatter< ChildType >::operator<<(std::ios &(*x)(std::ios &))
ChildType& openage::util::StringFormatter< ChildType >::operator<<(std::ostream &(*x)(std::ostream &))
ChildType& openage::util::StringFormatter< ChildType >::operator<<(const char *s)
ChildType& openage::util::StringFormatter< ChildType >::operator<<(const std::string &s)
ChildType& openage::util::StringFormatter< ChildType >::fmt(const char *fmt,...) ATTRIBUTE_FORMAT(2
Referenced by openage::event::demo::BallReflectPanel::invoke, openage::event::demo::ResetGame::invoke, openage::event::demo::BallReflectWall::predict_invoke_time, openage::event::demo::BallReflectPanel::predict_invoke_time.
ChildType ChildType& openage::util::StringFormatter< ChildType >::operator<<(const std::unique_ptr< T > &ptr)
ChildType& openage::util::StringFormatter< ChildType >::operator<<(const std::shared_ptr< T > &ptr)
void openage::util::StringFormatter< ChildType >::reset_flags()
Clears the underlying stream object's flags, if such a stream object exists.
virtual bool openage::util::StringFormatter< ChildType >::should_format() const
Returns if formatting should actually occur.
void openage::util::StringFormatter< ChildType >::ensure_stream_obj()
Ensures that we have a valid CachableOSStream object in stream_ptr.