qtsdl::RecursiveDirectoryWatcher
std::future<void> qtsdl::RecursiveDirectoryWatcher::worker
Referenced by RecursiveDirectoryWatcher, ~RecursiveDirectoryWatcher.
qtsdl::RecursiveDirectoryWatcher::RecursiveDirectoryWatcher(QObject *parent=nullptr)
References qtsdl::RecursiveDirectoryWatcherWorker::changeDetected, changeDetected, qtsdl::RecursiveDirectoryWatcherWorker::onRootDirsPathsChanged, quit, rootDirsPathsChanged, worker.
qtsdl::RecursiveDirectoryWatcher::~RecursiveDirectoryWatcher()
References quit, worker.
void qtsdl::RecursiveDirectoryWatcher::changeDetected()
Referenced by qtsdl::GuiEngineImpl::GuiEngineImpl, RecursiveDirectoryWatcher.
void qtsdl::RecursiveDirectoryWatcher::rootDirsPathsChanged(const QStringList &)
Referenced by qtsdl::GuiEngineImpl::GuiEngineImpl, RecursiveDirectoryWatcher.
void qtsdl::RecursiveDirectoryWatcher::quit()
Referenced by RecursiveDirectoryWatcher, ~RecursiveDirectoryWatcher.