openage::gui::GuiGameSpecImageProviderByFilenameImpl
openage::gui::GuiGameSpecImageProviderByFilenameImpl::GuiGameSpecImageProviderByFilenameImpl(qtsdl::GuiEventQueue *render_updater)
openage::gui::GuiGameSpecImageProviderByFilenameImpl::~GuiGameSpecImageProviderByFilenameImpl()
const char * openage::gui::GuiGameSpecImageProviderByFilenameImpl::id()
Referenced by get_id, openage::gui::GuiImageProviderLink::provider_by_filename.
const char * openage::gui::GuiGameSpecImageProviderByFilenameImpl::get_id() const override
References id.
Referenced by get_texture_handle.
TextureHandle openage::gui::GuiGameSpecImageProviderByFilenameImpl::get_texture_handle(const QString &id) override
References ENSURE, openage::util::filename, get_id, openage::gui::GuiGameSpecImageProviderImpl::get_missing_texture, openage::gui::GuiGameSpecImageProviderImpl::loaded_game_spec.