openage::Resource
openage::Resource::Resource()
virtual int openage::Resource::id() const =0
Referenced by openage::ResourceBundle::get, openage::ResourceBundle::operator[].
virtual std::string openage::Resource::name() const =0
Referenced by openage::ResourceProducer::ResourceProducer, openage.util.fslike.path.Path.stem, openage.util.fslike.path.Path.suffix, openage.util.fslike.path.Path.suffixes.