openage::UnitTypeMeta
using openage::UnitTypeMeta::type_ptr = std::shared_ptr<UnitType>
using openage::UnitTypeMeta::init_func = std::function<type_ptr(const Player &owner)>
const init_func openage::UnitTypeMeta::init
creates the base unit type for a player
const std::string openage::UnitTypeMeta::type_name
Referenced by openage.convert.dataformat.members.EnumMember.__repr__, openage.convert.dataformat.members.MultisubtypeMember.__repr__, openage.convert.dataformat.members.EnumLookupMember.entry_hook, openage.convert.dataformat.members.RefMember.format_hash, openage.convert.dataformat.members.EnumMember.get_effective_type, openage.convert.dataformat.members.MultisubtypeMember.get_effective_type, openage.convert.dataformat.members.EnumMember.get_parsers, openage.convert.dataformat.members.EnumMember.get_snippets, openage.convert.dataformat.members.MultisubtypeMember.get_snippets, openage.convert.dataformat.members.MultisubtypeMember.get_typerefs, name, UnitTypeMeta.
const int openage::UnitTypeMeta::type_id
Referenced by id, UnitTypeMeta.
openage::UnitTypeMeta::UnitTypeMeta(const std::string &name, int id, init_func f)
References name, type_id, type_name.
std::string openage::UnitTypeMeta::name() const
References type_name.
Referenced by openage.util.fslike.path.Path.stem, openage.util.fslike.path.Path.suffix, openage.util.fslike.path.Path.suffixes, UnitTypeMeta, openage::UnitType::~UnitType.
int openage::UnitTypeMeta::id() const
References type_id.
Referenced by openage::UnitType::~UnitType.