openage::OutputModeSignals
void openage::OutputModeSignals::announced(const std::string &name)
Signal is triggered to anounce a new output mode.
name: name of the gui mode.
Referenced by openage::OutputMode::announce, openage::gui::OutputModeLink::OutputModeLink.
void openage::OutputModeSignals::binds_changed(const std::vector< std::string > &binds)
Signal is triggered when the bindings of the mode change.
binds: list of strings that describe keybindings.
Referenced by openage::OutputMode::announce, openage::gui::OutputModeLink::OutputModeLink.