openage::util::fslike::Python
std::shared_ptr<py::Obj> openage::util::fslike::Python::fsobj
Referenced by openage.util.fslike.path.Path.__eq__, openage.util.fslike.path.Path.__repr__, openage.util.fslike.path.Path.__str__, openage.util.fslike.path.Path._get_native_path, openage.util.fslike.path.Path._resolve_r, openage.util.fslike.path.Path._resolve_w, openage.util.fslike.filecollection.FileCollectionPath.add_file, openage.util.fslike.path.Path.exists, openage.util.fslike.path.Path.filesize, get_filesize, get_mtime, get_native_path, get_py_fsobj, is_dir, openage.util.fslike.path.Path.is_dir, is_file, openage.util.fslike.path.Path.is_file, openage.util.fslike.path.Path.iterdir, openage.util.fslike.path.Path.joinpath, list, openage.util.fslike.path.Path.list, mkdirs, openage.util.fslike.path.Path.mkdirs, openage.util.fslike.union.UnionPath.mount, openage.util.fslike.path.Path.mtime, openage.util.fslike.path.Path.open, open_a, open_ar, open_r, openage.util.fslike.path.Path.open_r, open_rw, open_w, openage.util.fslike.path.Path.open_w, openage.util.fslike.path.Path.parent, openage.util.fslike.path.Path.poll_fs_watches, Python, rename, openage.util.fslike.path.Path.rename, repr, resolve_r, resolve_w, rmdir, openage.util.fslike.path.Path.rmdir, touch, openage.util.fslike.path.Path.touch, unlink, openage.util.fslike.path.Path.unlink, openage.util.fslike.union.UnionPath.unmount, openage.util.fslike.path.Path.watch, writable, openage.util.fslike.path.Path.writable.
openage::util::fslike::Python::Python(py::Obj fsobj)
References fsobj.
bool openage::util::fslike::Python::is_file(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_is_file.
Referenced by openage.util.fslike.abstract.FSLikeObject.exists.
bool openage::util::fslike::Python::is_dir(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_is_dir.
Referenced by openage.util.fslike.abstract.FSLikeObject.exists, openage.util.fslike.path.Path.removerecursive.
bool openage::util::fslike::Python::writable(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_writable.
Referenced by openage.util.fslike.wrapper.Wrapper.resolve_w, openage.util.fslike.abstract.FSLikeObject.resolve_w.
std::vector< Path::part_t > openage::util::fslike::Python::list(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_list.
bool openage::util::fslike::Python::mkdirs(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_mkdirs.
Referenced by openage.util.fslike.wrapper.DirectoryCreator.open_w.
File openage::util::fslike::Python::open_r(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_open_r.
File openage::util::fslike::Python::open_w(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_open_w.
File openage::util::fslike::Python::open_rw(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_open_rw.
File openage::util::fslike::Python::open_a(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_open_a.
File openage::util::fslike::Python::open_ar(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_open_ar.
std::pair< bool, Path > openage::util::fslike::Python::resolve_r(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_resolve_r.
std::pair< bool, Path > openage::util::fslike::Python::resolve_w(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_resolve_w.
std::string openage::util::fslike::Python::get_native_path(const Path::parts_t &parts) override
References openage::pyinterface::PyObjectRef::bytes, fsobj, openage::pyinterface::PyObjectRef::is, openage::util::fslike::pyx_fs_get_native_path.
bool openage::util::fslike::Python::rename(const Path::parts_t &parts, const Path::parts_t &target_parts) override
References fsobj, openage::util::fslike::pyx_fs_rename.
bool openage::util::fslike::Python::rmdir(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_rmdir.
Referenced by openage.util.fslike.path.Path.removerecursive.
bool openage::util::fslike::Python::touch(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_touch.
bool openage::util::fslike::Python::unlink(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_unlink.
Referenced by openage.util.fslike.path.Path.removerecursive.
int openage::util::fslike::Python::get_mtime(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_get_mtime.
uint64_t openage::util::fslike::Python::get_filesize(const Path::parts_t &parts) override
References fsobj, openage::util::fslike::pyx_fs_get_filesize.
bool openage::util::fslike::Python::is_python_native() const noexcept override
py::Obj & openage::util::fslike::Python::get_py_fsobj() const
References fsobj.
std::ostream & openage::util::fslike::Python::repr(std::ostream &) override
References fsobj.