openage::coord::input
viewport openage::coord::input::to_viewport(const CoordManager &mgr) const
References openage::coord::camgame_delta::to_viewport.
Referenced by openage::EditorMode::on_game_control_set.
camgame openage::coord::input::to_camgame(const CoordManager &mgr) const
References openage::coord::viewport_delta::to_camgame, openage::coord::camgame_delta::to_viewport.
Referenced by openage::ActionMode::on_game_control_set.
phys3 openage::coord::input::to_phys3(const CoordManager &mgr, phys_t up=phys_t::zero()) const
References openage::coord::viewport_delta::to_camgame, openage::coord::camgame_delta::to_phys3, openage::coord::camgame_delta::to_viewport.
Referenced by openage::ActionMode::on_game_control_set.