openage::gui::OutputModeLink
QString OutputModeLink::name
Referenced by openage.convert.dataformat.header_snippet.HeaderSnippet.__eq__, openage.convert.dataformat.header_snippet.HeaderSnippet.__hash__, openage.convert.dataformat.header_snippet.HeaderSnippet.__repr__, openage.convert.dataformat.header_snippet.HeaderSnippet.get_file_name, OutputModeLink, openage.util.fslike.path.Path.stem, openage.util.fslike.path.Path.suffix, openage.util.fslike.path.Path.suffixes.
QStringList OutputModeLink::binds
Referenced by OutputModeLink.
OutputModeLink::OutputModeLink(QObject *parent=nullptr)
References openage::ActionModeSignals::ability_changed, openage::gui::ActionModeLink::act, openage::gui::ActionModeLink::action_triggered, openage::gui::ActionModeLink::ActionModeLink, openage::OutputModeSignals::announced, binds, openage::OutputModeSignals::binds_changed, binds_changed, openage::building, openage::ActionModeSignals::buttons_type_changed, classBegin, componentComplete, openage::gui::CreateModeLink::CreateModeLink, openage::damaged, openage::gui::EditorModeLink::EditorModeLink, openage::garrison, openage::gui::ActionModeLink::get_ability, openage::Unit::get_attribute, get_binds, get_name, openage::gui::ActionModeLink::get_population, openage::gui::ActionModeLink::get_population_warn, openage::gui::ActionModeLink::get_selection_size, openage::Unit::has_attribute, openage::hitpoints, qtsdl::GuiItemMethods< OutputModeLink >::i, openage::UnitType::icon, openage::UnitType::id, openage::Player::is_ally, name, openage::UnitType::name, openage::UnitAction::name, name_changed, openage::gui::ActionModeLink::on_ability_changed, openage::ActionModeSignals::on_action, on_announced, on_binds_changed, openage::gui::ActionModeLink::on_buttons_type_changed, on_core_adopted, openage::gui::ActionModeLink::on_core_adopted, openage::gui::ActionModeLink::on_population_changed, openage::gui::ActionModeLink::on_selection_changed, openage::owner, openage::population, openage::ActionModeSignals::population_changed, openage::gui::ActionModeLink::progress, openage::gui::QQmlParserStatus, ref, openage::resource, qtsdl::GuiItemMethods< OutputModeLink >::s, openage::ActionModeSignals::selection_changed, std::to_string, openage::Unit::top, openage::UnitType::unit_class, openage::Unit::unit_type, qtsdl::unwrap, openage::log.warn, openage::gui::ActionModeLink::~ActionModeLink, openage::gui::CreateModeLink::~CreateModeLink, ~OutputModeLink.
virtual openage::gui::OutputModeLink::~OutputModeLink()
Referenced by OutputModeLink.
QString openage::gui::OutputModeLink::get_name() const
Referenced by OutputModeLink.
QStringList openage::gui::OutputModeLink::get_binds() const
Referenced by OutputModeLink.
void openage::gui::OutputModeLink::name_changed()
Referenced by OutputModeLink.
void openage::gui::OutputModeLink::binds_changed()
Referenced by OutputModeLink.
void openage::gui::OutputModeLink::on_announced(const std::string &name)
Referenced by OutputModeLink.
void openage::gui::OutputModeLink::on_binds_changed(const std::vector< std::string > &binds)
Referenced by OutputModeLink.
virtual void openage::gui::OutputModeLink::classBegin() override
Referenced by OutputModeLink.
virtual void openage::gui::OutputModeLink::on_core_adopted() override
Referenced by OutputModeLink.
virtual void openage::gui::OutputModeLink::componentComplete() override
Referenced by OutputModeLink.